### ISSUE TITLE
Feature request (if possible)

### ISSUE THREAD

**Issue by Theguru123** [rithik-b/PlaylistManager#26]
First off thank you for a great mod!!!

Is there a way you can enable continuous mode? i.e play all the songs in the playlist without a break between each song? so there are no results at the end each song menu etc.. until the last song show only the last song results maybe??...I think it would be great for exercising!!

i remember there was a mod a while back but that is no longer updated and it never really worked anyway lol...but yours would be perfect!!

**Comment by rithik-b** [comment]
Unfortunately due to 3 main reasons this would be impossible to implement:
- Results: Not going back to the results screen means that the results of your play won’t be stored at all. I may also need to disable score submission for the last song so it doesn’t show an absurdly high number for the score.
- Difficulties: If songs with multiple difficulties exist, which one will it choose for continuous mode? The highest? Lowest? Highlighted? What if multiple difficulties were highlighted, what then?
- Maintainability: This sounds like a feature that could complicate the mod and easily make it break with upcoming updates. Since this is the only playlist loading mod for PC and people care about using it as soon as new updates are out, I cannot commit to maintaining a feature like this or have it hold back the whole mod, sorry.
