### ISSUE TITLE
Account for MAX_PATH when extracting songs

### ISSUE THREAD

**Issue by Meivyn** [rithik-b/PlaylistManager#37]
This is going to throw an exception if `entryPath` exceeds `MAX_PATH`, which is around 255-260 characters on Windows.

https://github.com/rithik-b/PlaylistManager/blob/e39fe6559f98366396b9f71bace5566229d62c32/PlaylistManager/Utilities/DownloaderUtils.cs#L163-L168

![image](https://user-images.githubusercontent.com/793322/143922498-bcc59b1f-e1a0-42e0-9332-7d7b7efd2ce7.png)

@Top-Cat will probably limit the song name/author fields on BeatSaver, but I am opening an issue just in case.

**Comment by Top-Cat** [comment]
I don't think it would be a bad idea to limit the folder names anyway in PlaylistManager/BeatSaverDownloader

If you have a song name like "An artifice (that would have disrupted the far old monarchy in the course of time)" do you really need to have all that in the folder name? It's unlikely that people would actually be able to read all of that in file explorer.

**Comment by rithik-b** [comment]
Alright with some thinking on this situation here is what I propose
Since this is max path, and we get not much control on where the user places their beat saber folder (the upper directories could have long names)
I propose to limit the folder name to 50 characters (which seems to be the upper limit of something glanceable in file explorer)
If we go above 260 still, user issue
