### ISSUE TITLE
[Feature] Automatically updating playlist

### ISSUE THREAD

**Issue by Chr0mia** [rithik-b/PlaylistManager#42]
It would be cool to have a type of playlist with for example qualified maps that automatically update when a song gains the status of qualified. This could also be done with ranked maps.

I got this idea with the new surge of ranked maps and i found myself having trouble finding what maps i already had downloaded before and which ones i needed. It didn't help that the game said i had songs which i, in fact, did not have.

Making this automated could significantly improve quality of life in terms of Ranked, As you can launch the game and instantly see which maps are qualified, and if a map gains the status of ranked it would be removed and then later could be found by using the ranked filter.

It would be an all around smoother experience

**Comment by rithik-b** [comment]
Couple of clarifications:
- PlaylistManager does not offer any playlists but loads existing ones
- PlaylistManager does not offer any filtering, BetterSongList and SongBrowser do so this mod doesn’t control the Ranked filter
- Automatically syncing playlists isn’t an option because playlists are pretty large files and downloading potentially 100s of playlist files upon startup of the game, yeah no one wants that it will be an awful experience

**Comment by rithik-b** [comment]
https://github.com/kinsi55/BeatSaber_BetterSongSearch/releases/tag/v0.7.0 oh and BetterSongSearch's latest release on Github has a feature for creating playlists like ranked playlists ingame so you can use that
