### ISSUE TITLE
(1.37) PlaylistManager UI overlapping with other mods

### ISSUE THREAD

**Issue by drummerXD** [rithik-b/PlaylistManager#72]
This happens specifically when you have more than 3 playlists, and hovering over playlists extend all other playlist covers out. This breaks the position and makes other buttons around PlaylistManager's buttons overlap.

![image](https://github.com/user-attachments/assets/16725ea4-e9c6-48c4-8421-7c043c0e9e87)

I reported this to the BeatSaberPlus discord, but they said it's a PlaylistManager issue. Also notice that in the screenshot above, the WIP button is also pushed over. wipbot is unrelated to BeatSaberPlus
![image](https://github.com/user-attachments/assets/96eb3a9d-92a8-471a-b9dc-f2d63f89a1e9)

Mod version 1.7.1 and game version 1.37.1 (the BSManager recommended)

**Comment by Meivyn** [comment]
Report this directly to HardCPP, I'm not messing up with that UI anymore. Hope they fix it on their side or deal with it. This UI is a pain to work with. Or ask them to make a PR if they rather want this fixed in PM.

I moved the UI and changed its size which is why this behavior happens. https://github.com/rithik-b/PlaylistManager/blob/d3a395a741898590059150d53a7462c8c16c58e3/PlaylistManager/AffinityPatches/AnnotatedBeatmapLevelCollectionsUIPatches.cs#L8

**Comment by Meivyn** [comment]
If this specifically happens when hovering over the playlists, it might be related to #74. In which case it should be fixed in the next version.

**Comment by Meivyn** [comment]
There hasn't been any news from you and it seems to be fixed according to other users, so closing.
